# Generated by Django 3.0.5 on 2023-05-03 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gyro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Horn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horn_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_id', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('timestamp', models.TimeField()),
                ('gyro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Gyro')),
                ('horn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Horn')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.Location')),
            ],
        ),
    ]
