# Generated by Django 3.0.5 on 2023-05-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('horn', models.IntegerField()),
                ('gyro', models.CharField(max_length=30)),
                ('gps', models.CharField(max_length=30)),
            ],
        ),
    ]
